### PR TITLE
Updated Light-mode

### PR DESCRIPTION
**Pull request by SikandarJODD**
Updated Light Mode

### CODE REVIEW

**Comment by ieedan** [comment]
Looks like you copy pasted the +layout component and removed some previous changes

**Comment by SikandarJODD** [comment]
> Looks like you copy pasted the +layout component and removed some previous changes

yes i did few changes like change the color in +layout and changed the text-gray-300 to text-gray-600 simple ...

**Comment by ieedan** [comment]
> > Looks like you copy pasted the +layout component and removed some previous changes
> 
> yes i did few changes like change the color in +layout and changed the text-gray-300 to text-gray-600 simple ...

You removed links to 2 components and the new algorithim for the edit button accidentally I think

**Comment by ieedan** [comment]
image

**Comment by SikandarJODD** [comment]
> image

i need to look it again wait a min

**Pull request closed without merging**
