### PR TITLE
Features jod

### PR DESCRIPTION
**Pull request by SikandarJODD**
Changes : Solving #31 
### I have added : copy icon from /copy/clone icon from repo 
- it will help user to copy the code from **CODE** section
image

### Hero with Description 
image
- This Includes a Small Description for user to specify the project - added type="p" 
### in:fade  animation in *Details* under Feildset
image

### CODE REVIEW

**Comment by ieedan** [comment]
I love the copy animation on the code looks great can you add the same thing to `Snippet`?

**Comment by ieedan** [comment]
The details component has a conflict can you look at the transition I added this morning and let me know which one you like better?

**Comment by ieedan** [comment]
Add `align="center"` to headings in thirdExample on hero

**Comment by SikandarJODD** [comment]
Yes i will go through all the changes u mentioned.

**Comment by SikandarJODD** [comment]
> The details component has a conflict can you look at the transition I added this morning and let me know which one you like better?

I liked the in:fade animation for details

**Comment by SikandarJODD** [comment]
i look at your animation code i didn't get how to resolve the conflict ...

**Comment by ieedan** [comment]
> > The details component has a conflict can you look at the transition I added this morning and let me know which one you like better?
> 
> I liked the in:fade animation for details

I'm kinda liking the drawer animation better it kinda keeps up better with the resize I think. You turned it on with the animate={true} when you tested it right?

**Comment by SikandarJODD** [comment]
> > > The details component has a conflict can you look at the transition I added this morning and let me know which one you like better?
> > 
> > 
> > I liked the in:fade animation for details
> 
> I'm kinda liking the drawer animation better it kinda keeps up better with the resize I think. You turned it on with the animate={true} when you tested it right?

ooooo yes this drawer animation look cool

**Comment by ieedan** [comment]
Everything pretty much looks good 

On /hero/+page.svelte the code example doesn't match the actual code

**Comment by ieedan** [comment]
This is the first outside PR I have got so its failing because it isnt allowing the token to be used. Can you close and reopen this to see if the settings change allows it to run?

**Comment by ieedan** [comment]
Sorry I'm trying to get this to work but I'm not really sure how to allow the access I approved the runs that should do it?

**Comment by ieedan** [comment]
Can you merge my workflow changes from main and lets see if that fixes the CI / CD

**Comment by ieedan** [comment]
Hopefully it just works and then it won't happen again

**Comment by ieedan** [comment]
I will update the actions so this doesnt happen again thanks for being patient

**Pull request merged**
