### PR TITLE
final update light-mode 

### PR DESCRIPTION
**Pull request by SikandarJODD**
100th branch updating a simple light mode ..i mean i m dumb right now

### CODE REVIEW

**Comment by SikandarJODD** [comment]
i don't understand this stuff i just changed 3 lines 10 time...and it shows 
<code>+24 −45</code> as file changed...

**Comment by ieedan** [comment]
lgtm just format and lint so it passes CI

**Comment by ieedan** [comment]
Oh no not this again

**Comment by ieedan** [comment]
> i don't understand this stuff i just changed 3 lines 10 time...and it shows `+24 −45` as file changed...

I think its formatting maybe

**Comment by SikandarJODD** [comment]
> lgtm just format and lint so it passes CI

as per the last pr i use those command : npm run format and npm run lint it literally modified : all the files and i was shocked

**Comment by SikandarJODD** [comment]
> Oh no not this again

image
image
image

**Comment by ieedan** [comment]
> > lgtm just format and lint so it passes CI
> 
> as per the last pr i use those command : npm run format and npm run lint it literally modified : all the files and i was shocked

Yeah idk why it does that sometimes luckily it doesnt show up in the dif.

Deployment is passing I am just gonna merge I still don't know why it won't let you check out the code

**Comment by SikandarJODD** [comment]
> > > lgtm just format and lint so it passes CI
> > 
> > 
> > as per the last pr i use those command : npm run format and npm run lint it literally modified : all the files and i was shocked
> 
> Yeah idk why it does that sometimes luckily it doesnt show up in the dif.
> 
> Deployment is passing I am just gonna merge I still don't know why it won't let you check out the code

might be he know i m dumb

**Pull request merged**
