### PR TITLE
Added required field in all forms

### PR DESCRIPTION
**Pull request by ace-cltr**
Add required form to project related to issue #258.

- Added required validation for all input fields.
- Updated see the code below section with same code.
- Added symbol like '*' to indicate field is required to the user.

# Checks 🗸

-   [ 🗸] npm run format # prettier format
-   [🗸 ] npm run lint # eslint check
-   [ 🗸] npm run package # checks ability to package
-   [ 🗸] npm run build # make sure build will pass

### CODE REVIEW

**Comment by ieedan** [comment]
When I get back to my desk I will improve the original issue I opened. This is a good step forwards for documentation though.

**Comment by ace-cltr** [comment]
Thanks for the feedback! I look forward to the updated issue details, I had a feeling that you are not asking for something this basic.

**Comment by ieedan** [comment]
See updated issue https://github.com/ieedan/geist-ui-svelte/issues/258#issuecomment-2142710412

**Comment by ieedan** [comment]
Im gonna close this for now

**Pull request closed without merging**
