### PR TITLE
updated light-mode

### PR DESCRIPTION
**Pull request by SikandarJODD**
#Updated Light Mode : 
Preview : 
image

# Dark Mode : 
image

## Changes : 2 File Changed : /components/+layout.svelte & NavRoute.svelte minor changes

### CODE REVIEW

**Comment by ieedan** [comment]
Looks good but you need to pull from main you are way behind.

**Comment by SikandarJODD** [comment]
should i make changes in main branch and make a pull req ?

**Comment by ieedan** [comment]
If you are using github desktop you should be able to just update the branch from main. 

I don't know the CLI well enough to tell you how to do it that way.

You could also create a new branch from main and make your changes there

**Comment by ieedan** [comment]
image

**Comment by SikandarJODD** [comment]
> image

i did the same think i did git pull in main branch then created a seperate branch then changed it..and made a pr

**Comment by SikandarJODD** [comment]
ok i got the issue wait a min

**Pull request closed without merging**
